spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

clamav.host=${CLAMAV_HOST:127.0.0.1}
clamav.port=${CLAMAV_PORT:3310}

jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS:7200000}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

brevo.api.key=${BREVO_API_KEY}

cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}